#!/bin/bash
usage() {
	>&2 echo "Error: Expected input: [test suite file] [test program file]"
}
if [ $# -ne 2 ]; then
	usage
	exit 1
fi
for line in $(cat ${1})
do
	if [ -r ${line}.in -a -r ${line}.out ]; then
		temp=`mktemp /tmp/${line}.XXXXXXXX`
		if [ -a ${line}.args ]; then
			if [ -r ${line}.args ]; then
				args=$(cat ${line}.args)
				cat ${line}.in | ./${2} ${args} > $temp
			else
				>&2 echo "Error: could not read file ${line}.args"
				exit 3
			fi
		else
			cat ${line}.in | ./${2} > $temp
		fi
		if [[ -n $(diff ${line}.out ${temp}) ]]; then
			echo "Test failed: ${line}"
			echo "Input:"
			cat ${line}.in
			echo "Expected:"
			cat ${line}.out
			echo "Actual:"
			cat ${temp}
		fi
		rm ${temp}
	else
		>&2 echo "Error: Unable to read or find files ${line}.in or ${line}.out"
		exit 2
	fi
done